import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
const base=new URL('../',import.meta.url);
const guides={};
for(const name of ['README.md','README_jp.md']) guides['/'+name]=await readFile(new URL('ui/'+name,base),'utf8');
await writeFile(new URL('ui/guide.js',base),`// Generated from README.md / README_jp.md by scripts/prepare.mjs\nexport const guides = ${JSON.stringify(guides)};\nexport function withGuide(files) { return {...files, ...guides}; }\nexport function isGuide(path) { return Object.hasOwn(guides, path); }\nexport function canRun(path) { return /\\.(m?js)$/i.test(path); }\n`);

await mkdir(new URL('ui/vendor/',base),{recursive:true});
await copyFile(new URL('node_modules/es-module-lexer/dist/lexer.minimal.asm.js',base),new URL('ui/vendor/module-lexer.js',base));
await copyFile(new URL('node_modules/es-module-lexer/LICENSE',base),new URL('ui/vendor/module-lexer.LICENSE',base));

await cp(new URL('node_modules/monaco-editor/min/vs',base),new URL('ui/vendor/monaco/vs',base),{recursive:true});
for (const name of ['LICENSE','ThirdPartyNotices.txt']) await copyFile(new URL('node_modules/monaco-editor/'+name,base),new URL('ui/vendor/monaco/'+name,base));

await copyFile(new URL('node_modules/acorn/dist/acorn.mjs',base),new URL('ui/vendor/acorn.mjs',base));
await copyFile(new URL('node_modules/acorn/LICENSE',base),new URL('ui/vendor/acorn.LICENSE',base));

const examples={};
for(const name of ['01_multi_output.js','02_assigned_outputs.js','03_context_jsdoc.js','04_first_note.js','05_live_loop.js','06_multi_channel.js','07_external_output.js','08_output_slots.js'])examples['/examples/'+name]=await readFile(new URL('ui/examples/'+name,base),'utf8');
await writeFile(new URL('ui/example-files.js',base),`// Generated by scripts/prepare.mjs
export const bundledExamples = ${JSON.stringify(examples)};
`);

const apiTypes=await readFile(new URL('ui/playground-api.d.ts',base),'utf8');
await writeFile(new URL('ui/api-types.js',base),`// Generated by scripts/prepare.mjs
export const apiTypes = ${JSON.stringify(apiTypes)};
`);
